name: CommandBlackList
main: cbl.CommandBlackList
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1

permissions:
  commandblacklist.ignore:
    description: "Allows player to use blocked commands"
    default: op
